version: "3.8"

services:
  web:
    env_file:
      - .env
    build:
      context: '.docker/web'
      args:
        PHP_VERSION: ${PHP_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        NPM_VERSION: ${NPM_VERSION}
        YARN_VERSION: ${YARN_VERSION}
    restart: always
    networks:
      - backend
    ports:
      - "22:22"
    volumes:
      - ../.:/usr/local/apache2/htdocs/
    container_name: ${APP_NAME}_web
  apache:
    env_file:
      - .env
    build:
      context: '.docker/apache'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    restart: always
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ../.:/usr/local/apache2/htdocs/
    container_name: ${APP_NAME}_apache
  mysql:
    env_file:
      - .env
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TZ}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    networks:
      - backend
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    container_name: ${APP_NAME}_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - PMA_PORT=3306
      - PMA_HOST=mysql
    networks:
      - backend
    ports:
     - "8080:80"
    container_name: ${APP_NAME}_phpmyadmin
networks:
  frontend:
  backend:
volumes:
  data:
